dbt_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: **your-account-name**
      user: **your username**
      authenticator: externalbrowser
      role: **your_role**
      warehouse: **Your_warehouse
      database: HEALTHCARE_DW
      schema: ANALYTICS
      threads: 4
