SELECT
    CONSULTATION_ID,
    PATIENT_ID,
    DOCTOR_ID,
    CONSULTATION_TYPE,
    CONSULTATION_DATE,
    CHIEF_COMPLAINT,
    DIAGNOSIS,
    DIAGNOSIS_CODE,
    FOLLOW_UP_REQUIRED,
    FOLLOW_UP_DATE,
    NOTES,
    DURATION_MINUTES,
    CREATED_AT
FROM {{ source('healthcare_raw', 'consultations') }}
