SELECT
    PAYMENT_ID,
    ORDER_ID,
    PATIENT_ID,
    PAYMENT_DATE,
    AMOUNT,
    PAYMENT_METHOD,
    PAYMENT_STATUS,
    TRANSACTION_REF,
    INSURANCE_CLAIM_ID,
    INSURANCE_COVERED_AMOUNT,
    PATIENT_PAID_AMOUNT,
    CASE WHEN INSURANCE_CLAIM_ID IS NOT NULL THEN TRUE ELSE FALSE END AS is_insured,
    CREATED_AT
FROM {{ source('healthcare_raw', 'payments') }}
