SELECT
    ORDER_ID,
    PATIENT_ID,
    PRESCRIPTION_ID,
    ORDER_DATE,
    ORDER_STATUS,
    DELIVERY_TYPE,
    DELIVERY_ADDRESS,
    DELIVERY_CITY,
    DELIVERY_PIN_CODE,
    SUBTOTAL,
    DISCOUNT,
    DELIVERY_FEE,
    TOTAL_AMOUNT,
    EXPECTED_DELIVERY_DATE,
    ACTUAL_DELIVERY_DATE,
    DATEDIFF('day', ORDER_DATE, ACTUAL_DELIVERY_DATE) AS delivery_days,
    LAST_UPDATED
FROM {{ source('healthcare_raw', 'orders') }}
